import inceptionbg from "../images/inception-bg.jpeg";
import darkknightbg from "../images/dark-knight-bg.jpeg"
import interstellerbg from "../images/intersteller-bg.jpeg";
import avatarbg from "../images/avatar-bg.jpeg";


const moviesData = [
  {
    "_id": 1,
    "titleImg": "https://media.cimanow.cc/wp-content/uploads/2020/06/%D9%81%D9%8A%D9%84%D9%85-Interstellar-2014-%D9%85%D8%AA%D8%B1%D8%AC%D9%85-%D9%84%D9%88%D8%AC%D9%88.png",
    "bgImg": "https://resizing.flixster.com/47rDB5jGZrHWyRMRYMZKenbTcHU=/fit-in/705x460/v2/https://resizing.flixster.com/Y_sqtbGDcspx4oob3nD-lojSLjc=/ems.cHJkLWVtcy1hc3NldHMvbW92aWVzL2YyMWZjZTQ2LWQwZGItNGRhMi1hZjg3LWFhZDQ1YWU1OTQ2NC53ZWJw",
    "reviewImg": "https://images.bauerhosting.com/legacy/empire-tmdb/films/157336/images/xu9zaAevzQ5nnrsXN6JcahLnG4i.jpg?ar=16%3A9&fit=crop&crop=top&auto=format&w=undefined&q=80",
    "video": "videos/interstellar-trailer.mp4",
    "title": "Interstellar",
    "year": 2014,
    "date": "2014-11-07",
    "ageLimit": "10+",
    "length": "2h 49m",
    "category": ["Science Fiction", "Drama", "Action"],
    "type": "Movie",
    "description": "In a future where Earth faces ecological collapse, a team of explorers travels through a wormhole to find a new habitable planet. They confront unknown worlds, emotional challenges, and the limits of human survival as they try to save humanity.",
    "active": true
  },
  {
    "_id": 2,
    "titleImg": "../images/dark-knight-title.png",
    "bgImg": darkknightbg,
    "reviewImg": "https://theconsultingdetectivesblog.com/wp-content/uploads/2014/06/the-dark-knight-original.jpg",
    "video": "videos/dark-knight-trailer.mp4",
    "title": "The Dark Knight",
    "year": 2008,
    "date": "2008-07-18",
    "ageLimit": "13+",
    "length": "2h 32m",
    "category": ["Action", "Crime", "Drama"],
    "type": "Movie",
    "description": "Batman must confront the anarchic Joker, whose chaos threatens Gotham City. As lawlessness spreads, Batman faces moral dilemmas, intense battles, and the challenge of saving the city while protecting his own identity and those he loves.",
    "active": true
  },
  {
    "_id": 3,
    "titleImg": "../images/inception-title.png",
    "bgImg": inceptionbg,
    "reviewImg": "../images/inception-review.jpeg",
    "video": "videos/inception-trailer.mp4",
    "title": "Inception",
    "year": 2010,
    "date": "2010-07-16",
    "ageLimit": "13+",
    "length": "2h 28m",
    "category": ["Science Fiction", "Action", "Thriller"],
    "type": "Movie",
    "description": "A skilled thief enters the dreams of others to steal secrets. He faces complex layers of subconscious reality, betrayal, and personal guilt while trying to implant an idea in a target’s mind without losing himself in the process.",
    "active": true
  },
  {
    "_id": 4,
    "titleImg": "https://media.cimanow.cc/wp-content/uploads/2025/07/%D9%81%D9%8A%D9%84%D9%85-Wonder-Woman-2017-%D9%85%D8%AA%D8%B1%D8%AC%D9%85-%D9%84%D9%88%D8%AC%D9%88.png",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BMjEzYmZkNjktODBmYi00NzNkLWIzMjItMjhkMWZiZTZlN2MwXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    "reviewImg": "https://static1.cbrimages.com/wordpress/wp-content/uploads/2017/05/wonder-woman-fourth-trailer-feat-1.jpg",
    "video": "https://www.youtube.com/watch?v=1Q8fG0TtVAY",
    "title": "Wonder Woman",
    "year": 2017,
    "date": "2017-06-02",
    "ageLimit": "13+",
    "length": "2h 21m",
    "category": ["Action", "Adventure", "Fantasy"],
    "type": "Movie",
    "description": "Diana, princess of the Amazons, leaves her isolated homeland to fight in World War I. Along the way, she discovers her extraordinary powers, faces fierce enemies, and learns the true meaning of heroism and sacrifice.",
    "active": true
  },
  {
    "_id": 5,
    "titleImg": "images/avatar-title.png",
    "bgImg": avatarbg,
    "reviewImg": "https://snworksceo.imgix.net/dpn-34s/0a7855f2-7d69-4cdf-8b14-b5c59bd1bf03.sized-1000x1000.jpg?w=1000",
    "video": "videos/avatar-trailer.mp4",
    "title": "Avatar",
    "year": 2009,
    "date": "2009-12-18",
    "ageLimit": "10+",
    "length": "2h 42m",
    "category": ["Fantasy", "Adventure", "Action"],
    "type": "Movie",
    "description": "A paraplegic Marine is sent to the alien world of Pandora. Immersed in its culture and environment, he forms bonds with its inhabitants and discovers new perspectives, challenging his loyalties and understanding of humanity.",
    "active": true
  },
  {
    "_id": 6,
    "titleImg": "images/joker-title.png",
    "bgImg": "https://m.media-amazon.com/images/I/51E+o6036kL._UF894,1000_QL80_.jpg",
    "reviewImg": "images/joker-review.jpg",
    "video": "videos/joker-trailer.mp4",
    "title": "Joker",
    "year": 2019,
    "date": "2019-10-04",
    "ageLimit": "18+",
    "length": "2h 2m",
    "category": ["Drama", "Crime", "Thriller"],
    "type": "Movie",
    "description": "Arthur Fleck, a struggling comedian, slowly descends into madness. His frustrations and societal rejection transform him into the infamous Joker, creating chaos in Gotham City and challenging the limits of morality and sanity.",
    "active": true
  },
  {
    "_id": 7,
    "titleImg": "images/godfather-title.png",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BNGEwYjgwOGQtYjg5ZS00Njc1LTk2ZGEtM2QwZWQ2NjdhZTE5XkEyXkFqcGc@._V1_.jpg",
    "reviewImg": "https://images.bauerhosting.com/legacy/empire-tmdb/films/238/images/6xKCYgH16UuwEGAyroLU6p8HLIn.jpg?ar=16%3A9&fit=crop&crop=top&auto=format&w=1440&q=80",
    "video": "videos/godfather-trailer.mp4",
    "title": "The Godfather",
    "year": 1972,
    "date": "1972-03-24",
    "ageLimit": "18+",
    "length": "2h 55m",
    "category": ["Crime", "Drama"],
    "type": "Movie",
    "description": "The aging head of the Corleone crime family transfers control to his reluctant son. The family navigates betrayal, power struggles, and loyalty while maintaining its criminal empire in a dangerous and unpredictable world.",
    "active": true
  },
  {
    "_id": 8,
    "titleImg": "images/matrix-title.png",
    "bgImg": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRXIX7z5psGiGsBQUkANUHdtvym90-_eNP3UZUyqCasrTEnbm6W1wkfuSJ-gGSG4ScvtMg&usqp=CAU",
    "reviewImg": "https://i.guim.co.uk/img/media/5e0f098d236a9ac8174c47f0f798c85f9b5686fb/0_0_2496_1497/master/2496.jpg?width=1200&quality=85&auto=format&fit=max&s=377b9ca60b2ae37b85184ebf0249a609",
    "video": "videos/matrix-trailer.mp4",
    "title": "The Matrix",
    "year": 1999,
    "date": "1999-03-31",
    "ageLimit": "15+",
    "length": "2h 16m",
    "category": ["Science Fiction", "Action"],
    "type": "Movie",
    "description": "A hacker discovers that his reality is a simulated construct controlled by machines. He joins a rebellion to free humanity, facing philosophical dilemmas and deadly battles against agents enforcing the system.",
    "active": true
  },
  {
    "_id": 9,
    "titleImg": "https://image.tmdb.org/t/p/w500/7tRr9O5T4HkY7sYkd5eTl1SZZQA.jpg",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BNDhlMzEyNzItMTA5Mi00YWRhLThlNTktYTQyMTA0MDIyNDEyXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    "reviewImg": "https://thecosmiccircus.com/wp-content/uploads/2021/10/The-Pirates-of-the-Caribbean-The-Curse-of-the-Black-Pearl-e1648961317393.jpg",
    "video": "https://www.youtube.com/watch?v=naQr0uTrH_s",
    "title": "Pirates of the Caribbean: The Curse of the Black Pearl",
    "year": 2003,
    "date": "2003-07-09",
    "ageLimit": "13+",
    "length": "2h 23m",
    "category": ["Action", "Adventure", "Fantasy"],
    "type": "Movie",
    "description": "Blacksmith Will Turner teams with pirate Jack Sparrow to rescue the governor’s daughter and recover a cursed treasure. They face supernatural forces, dangerous rivals, and treacherous seas in this swashbuckling adventure full of humor and action.",
    "active": true
  },
  {
    "_id": 10,
    "titleImg": "https://media.cimanow.cc/wp-content/uploads/2021/05/%D9%81%D9%8A%D9%84%D9%85-Cruella-2021-%D9%85%D8%AA%D8%B1%D8%AC%D9%85-%D9%84%D9%88%D8%AC%D9%88.png",
    "bgImg": "https://images.moviesanywhere.com/72628135a01e28dbd3de510a70f39ad1/51843284-b466-458a-968d-21a5038f39be.jpg",
    "reviewImg": "https://media.cimanow.cc/wp-content/uploads/2021/05/%D9%81%D9%8A%D9%84%D9%85-Cruella-2021-%D9%85%D8%AA%D8%B1%D8%AC%D9%85-%D9%83%D9%88%D9%81%D8%B1.jpg",
    "video": "videos/cruella-trailer.mp4",
    "title": "Cruella",
    "year": 2021,
    "date": "2021-05-28",
    "ageLimit": "13+",
    "length": "2h 14m",
    "category": ["Crime", "Comedy", "Drama"],
    "type": "Movie",
    "description": "Young Estella navigates 1970s London, aspiring to become a fashion designer. As she grows, her rebellious and cunning nature emerges, leading her to embrace her alter ego, Cruella, in a world of high fashion, rivalry, and personal ambition.",
    "active": true
  },
  {
    "_id": 11,
    "titleImg": "images/lotr-title.png",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BNzIxMDQ2YTctNDY4MC00ZTRhLTk4ODQtMTVlOWY4NTdiYmMwXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    "reviewImg": "https://ntvb.tmsimg.com/assets/p28828_v_h8_ac.jpg?w=960&h=540",
    "video": "videos/lotr-trailer.mp4",
    "title": "The Lord of the Rings: The Fellowship of the Ring",
    "year": 2001,
    "date": "2001-12-19",
    "ageLimit": "10+",
    "length": "2h 58m",
    "category": ["Fantasy", "Adventure"],
    "type": "Movie",
    "description": "A young hobbit, Frodo, begins a dangerous journey to destroy a powerful ring that could bring darkness to Middle-earth, facing friends and foes along the way on a quest full of courage and discovery.",
    "active": true
  },
  {
    "_id": 12,
    "titleImg": "images/lotr2-title.png",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BMGQxMDdiOWUtYjc1Ni00YzM1LWE2NjMtZTg3Y2JkMjEzMTJjXkEyXkFqcGc@._V1_.jpg",
    "reviewImg": "https://m.media-amazon.com/images/S/pv-target-images/8bba1c2b8884ff4d6b1876b96f80a22eeeffb32a8863ce065c02c2453094a174.jpg",
    "video": "videos/lotr2-trailer.mp4",
    "title": "The Lord of the Rings: The Two Towers",
    "year": 2002,
    "date": "2002-12-18",
    "ageLimit": "10+",
    "length": "2h 59m",
    "category": ["Fantasy", "Adventure"],
    "type": "Movie",
    "description": "Frodo and Sam continue their perilous journey toward Mordor, while Aragorn, Legolas, and Gimli fight to protect Middle-earth from the growing power of Sauron and the evil forces gathering at Helm's Deep.",
    "active": true
  },
  {
    "_id": 13,
    "titleImg": "images/lotr3-title.png",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BMTZkMjBjNWMtZGI5OC00MGU0LTk4ZTItODg2NWM3NTVmNWQ4XkEyXkFqcGc@._V1_.jpg",
    "reviewImg": "https://musicart.xboxlive.com/7/79985000-0000-0000-0000-000000000002/504/image.jpg",
    "video": "videos/lotr3-trailer.mp4",
    "title": "The Lord of the Rings: The Return of the King",
    "year": 2003,
    "date": "2003-12-17",
    "ageLimit": "10+",
    "length": "3h 21m",
    "category": ["Fantasy", "Adventure"],
    "type": "Movie",
    "description": "The final battle for Middle-earth unfolds as Frodo and Sam approach Mount Doom to destroy the ring, while armies clash in epic battles to determine the fate of the world.",
    "active": true
  },
  {
    "_id": 14,
    "titleImg": "images/gladiator-title.png",
    "bgImg": "https://a.asd.homes/wp-content/uploads/2022/08/Gladiator-1-533x800.jpg",
    "reviewImg": "https://images.bauerhosting.com/legacy/empire-tmdb/films/98/images/5vZw7ltCKI0JiOYTtRxaIC3DX0e.jpg?ar=16:9&fit=crop&crop=top",
    "video": "videos/gladiator-trailer.mp4",
    "title": "Gladiator",
    "year": 2000,
    "date": "2000-05-05",
    "ageLimit": "16+",
    "length": "2h 35m",
    "category": ["Action", "Drama"],
    "type": "Movie",
    "description": "A betrayed Roman general seeks vengeance against the corrupt emperor who murdered his family, rising through the gladiatorial ranks to restore honor and justice in the heart of Rome.",
    "active": true
  },
  {
    "_id": 15,
    "titleImg": "images/titanic-title.png",
    "bgImg": "https://m.media-amazon.com/images/I/811lT7khIrL._UF1000,1000_QL80_.jpg",
    "reviewImg": "https://res.cloudinary.com/wemakeit/image/upload/c_thumb,f_auto,g_center,h_630,q_auto,w_1200/v1491384316/wemakeit/production/project/728/picture-e02fb828-f97b-4202-8a11-049defe52225.jpg",
    "video": "videos/titanic-trailer.mp4",
    "title": "Titanic",
    "year": 1997,
    "date": "1997-12-19",
    "ageLimit": "13+",
    "length": "3h 14m",
    "category": ["Romance", "Drama"],
    "type": "Movie",
    "description": "A young couple from different social classes fall in love aboard the Titanic, navigating societal pressures, personal challenges, and the tragedy of the ship's fateful maiden voyage.",
    "active": true
  },
  {
    "_id": 16,
    "titleImg": "https://media.cimanow.cc/wp-content/uploads/2020/05/%D9%81%D9%8A%D9%84%D9%85-The-Avengers-2012-%D9%85%D8%AA%D8%B1%D8%AC%D9%85-%D9%84%D9%88%D8%AC%D9%88.png",
    "bgImg": "https://upload.wikimedia.org/wikipedia/en/8/8a/The_Avengers_%282012_film%29_poster.jpg",
    "reviewImg": "https://variety.com/wp-content/uploads/2014/04/01-avengers-2012.jpg",
    "video": "videos/avengers-trailer.mp4",
    "title": "The Avengers",
    "year": 2012,
    "date": "2012-05-04",
    "ageLimit": "12+",
    "length": "2h 23m",
    "category": ["Superhero", "Action"],
    "type": "Movie",
    "description": "Earth’s mightiest heroes assemble to stop Loki and his alien forces from conquering Earth, learning to work together as a team to save humanity from imminent destruction.",
    "active": true
  },
  {
    "_id": 17,
    "titleImg": "https://media.cimanow.cc/wp-content/uploads/2020/06/%D9%81%D9%8A%D9%84%D9%85-Avengers-Endgame-2019-%D9%85%D8%AA%D8%B1%D8%AC%D9%85-%D9%84%D9%88%D8%AC%D9%88.png",
    "bgImg": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRaw6QTsDE3d6-qOL5xMa4-JDdBNTa3uspCrg&s",
    "reviewImg": "https://media.cimanow.cc/wp-content/uploads/2020/06/%D9%81%D9%8A%D9%84%D9%85-Avengers-Endgame-2019-%D9%85%D8%AA%D8%B1%D8%AC%D9%85-%D9%83%D9%88%D9%81%D8%B1-1.jpg",
    "video": "videos/endgame-trailer.mp4",
    "title": "Avengers: Endgame",
    "year": 2019,
    "date": "2019-04-26",
    "ageLimit": "12+",
    "length": "3h 2m",
    "category": ["Superhero", "Action"],
    "type": "Movie",
    "description": "After Thanos’ catastrophic snap, the Avengers regroup to undo his destruction, risking everything in a final mission that spans time and space to save the universe.",
    "active": true
  },
  {
    "_id": 18,
    "titleImg": "images/spiderman-title.png",
    "bgImg": "https://images.moviesanywhere.com/5a7e82e7749d6dd8e447fcfeec50c064/55462afc-41ad-4322-ad46-1caca29fcc36.jpg",
    "reviewImg": "https://wallpapers.com/images/featured/spider-man-no-way-home-pictures-l3ztimmzaeeqfgir.jpg",
    "video": "videos/spiderman-trailer.mp4",
    "title": "Spider-Man: No Way Home",
    "year": 2021,
    "date": "2021-12-17",
    "ageLimit": "12+",
    "length": "2h 28m",
    "category": ["Superhero", "Action"],
    "type": "Movie",
    "description": "Peter Parker seeks Doctor Strange’s help after his identity is revealed, leading to multiverse chaos where old allies and new threats challenge his courage and responsibility.",
    "active": true
  },
  {
    "_id": 19,
    "titleImg": "images/johnwick-title.png",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BMTU2NjA1ODgzMF5BMl5BanBnXkFtZTgwMTM2MTI4MjE@._V1_.jpg",
    "reviewImg": "https://m.media-amazon.com/images/M/MV5BMDE0ZjMzOTAtMzU2OS00ZDVmLWFlMjYtMThlOWYwMDBiN2E3XkEyXkFqcGdeQWFsZWxvZw@@._V1_QL75_UX500_CR0,0,500,281_.jpg",
    "video": "videos/johnwick-trailer.mp4",
    "title": "John Wick",
    "year": 2014,
    "date": "2014-10-24",
    "ageLimit": "18+",
    "length": "1h 41m",
    "category": ["Action", "Thriller"],
    "type": "Movie",
    "description": "An ex-hitman returns to the underworld to hunt down the gangsters responsible for killing his dog, igniting a relentless quest for vengeance against impossible odds.",
    "active": true
  },
  {
    "_id": 20,
    "titleImg": "https://upload.wikimedia.org/wikipedia/en/1/11/Annabelle_%28film%29_poster.jpg",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BNjkyMDU5ZWQtZDhkOC00ZWFjLWIyM2MtZWFhMDUzNjdlNzU2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    "reviewImg": "https://musicart.xboxlive.com/7/22815100-0000-0000-0000-000000000002/504/image.jpg",
    "video": "https://www.youtube.com/watch?v=VXk_RNV012s",
    "title": "Annabelle",
    "year": 2014,
    "date": "2014-10-03",
    "ageLimit": "16+",
    "length": "1h 39m",
    "category": ["Horror", "Thriller"],
    "type": "Movie",
    "description": "A couple experiences terrifying supernatural events when they bring home a vintage doll possessed by an evil spirit, unraveling dark secrets that threaten their sanity and safety.",
    "active": true
  },
  {
    "_id": 21,
    "titleImg": "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BMTczNTI2ODUwOF5BMl5BanBnXkFtZTcwMTU0NTIzMw@@._V1_FMjpg_UX1000_.jpg",
    "reviewImg": "https://image.tmdb.org/t/p/original/cyecB7godJ6kNHGONFjUyVN9OX5.jpg",
    "video": "https://www.youtube.com/watch?v=0WVDKZJkGlY",
    "title": "Iron Man",
    "year": 2008,
    "date": "2008-05-02",
    "ageLimit": "13+",
    "length": "2h 6m",
    "category": ["Action"],
    "type": "Movie",
    "description": "Tony Stark, a genius billionaire, builds the Iron Man suit to save his life and protect the world, facing dangerous enemies while learning responsibility and courage in a journey that changes him forever.",
    "active": true
  },
  {
    "_id": 22,
    "titleImg": "https://image.tmdb.org/t/p/w500/gh4CMhx7k8vhm1DGv4hG5VScT5X.jpg",
    "bgImg": "https://images.moviesanywhere.com/84076c825d1776e3d3e938118afa8f20/5e65557d-f358-4770-a26f-c56c9f1ebff4.jpg",
    "reviewImg": "https://the-cinema-critic.com/wp-content/uploads/2019/04/150848971.jpg",
    "video": "https://www.youtube.com/watch?v=xbqNb2PFKKA",
    "title": "The Incredible Hulk",
    "year": 2008,
    "date": "2008-06-13",
    "ageLimit": "13+",
    "length": "1h 52m",
    "category": ["Action"],
    "type": "Movie",
    "description": "Bruce Banner struggles to find a cure for his uncontrollable gamma-induced transformations, while avoiding the relentless pursuit of the military, forcing him to balance his life, morality, and responsibility for the destruction he can unleash.",
    "active": true
  },
  {
    "_id": 23,
    "titleImg": "https://image.tmdb.org/t/p/w500/1xU1dUCSmG2MCbTjXGnQOaA3u2Y.jpg",
    "bgImg": "https://m.media-amazon.com/images/I/61dC4+N3+0L._UF894,1000_QL80_.jpg",
    "reviewImg": "https://wallpapercave.com/wp/wp10220939.jpg",
    "video": "https://www.youtube.com/watch?v=Ke1Y3P9D0Bc",
    "title": "Iron Man 2",
    "year": 2010,
    "date": "2010-05-07",
    "ageLimit": "13+",
    "length": "2h 4m",
    "category": ["Action"],
    "type": "Movie",
    "description": "Tony Stark struggles with pressure from the government, new enemies, and personal health challenges while learning to manage his responsibilities as Iron Man and facing threats that endanger the world.",
    "active": true
  },
  {
    "_id": 24,
    "titleImg": "https://image.tmdb.org/t/p/w500/l2rK1t1lFkbck3dG7xLkgmZ1q9p.jpg",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BNjRhNGZjZjEtYTQzYS00OWUxLThjNGEtMTIwMTE2ZDFlZTZkXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    "reviewImg": "https://images.bauerhosting.com/legacy/empire-tmdb/films/10195/images/LvmmDZxkTDqp0DX7mUo621ahdX.jpg?ar=16%3A9&fit=crop&crop=top&auto=format&w=1440&q=80",
    "video": "https://www.youtube.com/watch?v=JOddp-nlNvQ",
    "title": "Thor",
    "year": 2011,
    "date": "2011-05-06",
    "ageLimit": "13+",
    "length": "1h 55m",
    "category": ["Action"],
    "type": "Movie",
    "description": "Thor, the god of thunder, is cast out of Asgard and sent to Earth, where he learns humility and responsibility while discovering his worth and preparing to defend the realms from cosmic threats.",
    "active": true
  },
  {
    "_id": 25,
    "titleImg": "https://image.tmdb.org/t/p/w500/5SSQErMlHDSrYhjSfkK2rxv9G3M.jpg",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BNzUyM2YyY2MtNzNlMS00MWU5LTgxNjAtNzZlNmI2NjU2NDZlXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    "reviewImg": "https://3238leblogdemarvelll-1278.kxcdn.com/wp-content/uploads/2011/07/Captain-America-First-Avenger-banniere.webp",
    "video": "https://www.youtube.com/watch?v=JerVrbLldXw",
    "title": "Captain America: The First Avenger",
    "year": 2011,
    "date": "2011-07-22",
    "ageLimit": "13+",
    "length": "2h 4m",
    "category": ["Action"],
    "type": "Movie",
    "description": "Steve Rogers, a scrawny young man, transforms into Captain America to fight Hydra during World War II, showcasing courage, leadership, and determination while shaping the destiny of heroes.",
    "active": true
  },
  {
    "_id": 26,
    "titleImg": "https://image.tmdb.org/t/p/w500/1g0dhYtq4irTY1GPXvft6k4YLjm.jpg",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BMTg1MTY2MjYzNV5BMl5BanBnXkFtZTgwMTc4NTMwNDI@._V1_FMjpg_UX1000_.jpg",
    "reviewImg": "https://www.framerated.co.uk/frwpcontent/uploads/2018/02/blackpanther01.jpg",
    "video": "https://www.youtube.com/watch?v=Hk0e7A0jNUI",
    "title": "Black Panther",
    "year": 2018,
    "date": "2018-02-16",
    "ageLimit": "13+",
    "length": "2h 14m",
    "category": ["Action"],
    "type": "Movie",
    "description": "T’Challa returns to Wakanda to assume the throne but faces threats from a powerful adversary, testing his leadership, courage, and commitment to protecting his nation and the world.",
    "active": true
  },
  {
    "_id": 27,
    "titleImg": "https://image.tmdb.org/t/p/w500/rDOKxh6gA9bS4JX7t4vTU3KQupK.jpg",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BMzNhNTE0NWQtN2E1Ny00NjcwLTg1YTctMGY1NmMwODJmY2NmXkEyXkFqcGc@._V1_.jpg",
    "reviewImg": "https://images.squarespace-cdn.com/content/v1/59d7e2c7e45a7c0ce235bb55/1562160924727-H385CR22LE6ZUU6E5LJ3/Spider-Man-Far-From-Home-Film-Review.jpg",
    "video": "https://www.youtube.com/watch?v=pZViqXvWbF8",
    "title": "Spider-Man: Far From Home",
    "year": 2019,
    "date": "2019-07-02",
    "ageLimit": "13+",
    "length": "2h 9m",
    "category": ["Action"],
    "type": "Movie",
    "description": "Peter Parker travels to Europe for school but is forced to confront new threats, testing his abilities as Spider-Man and forcing him to balance personal life with the responsibilities of being a hero.",
    "active": true
  },
  {
    "_id": 28,
    "titleImg": "https://image.tmdb.org/t/p/w500/gPbM0MK8CP8KMdX4ZC2n0blKaD.jpg",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BYTgxOWM2MWItNzJlZi00ZWViLWIzYjMtZThkZGJkYzMxYmRmXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    "reviewImg": "https://fr.web.img2.acsta.net/newsv7/19/02/26/18/11/4342746.jpg",
    "video": "https://www.youtube.com/watch?v=0rEnYCH4K7w",
    "title": "Captain Marvel",
    "year": 2019,
    "date": "2019-03-08",
    "ageLimit": "13+",
    "length": "2h 3m",
    "category": ["Action"],
    "type": "Movie",
    "description": "Carol Danvers becomes Captain Marvel and must confront intergalactic threats, learning to harness her powers, embrace her destiny, and fight to protect Earth and the universe from destructive forces.",
    "active": true
  },
  {
    "_id": 29,
    "titleImg": "https://image.tmdb.org/t/p/w500/lMgry7YxyG5Q2zZpFB2MkgOjLxB.jpg",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BMjMxNjY2MDU1OV5BMl5BanBnXkFtZTgwNzY1MTUwNTM@._V1_FMjpg_UX1000_.jpg",
    "reviewImg": "https://media.gq-magazine.co.uk/photos/5d138e9fb6fee94e70c9e01a/16:9/w_2560%2Cc_limit/https_2f2fblogs-imagesforbes.jpg",
    "video": "https://www.youtube.com/watch?v=0bgEhjMkP_k",
    "title": "Avengers: Infinity War",
    "year": 2018,
    "date": "2018-04-27",
    "ageLimit": "13+",
    "length": "2h 29m",
    "category": ["Action"],
    "type": "Movie",
    "description": "The Avengers and their allies must come together to prevent Thanos from collecting all the Infinity Stones, facing impossible odds and unimaginable challenges that threaten the entire universe.",
    "active": true
  },
  {
    "_id": 30,
    "titleImg": "https://image.tmdb.org/t/p/w500/8i6weHfT8L5rB9J7b8yKX7Kc3Lm.jpg",
    "bgImg": "https://play-lh.googleusercontent.com/Sxh2qo5repn6KAslfYzEr_pdlUNFUo1KRzxQWGALEFZ0PNxVl5mPSASE_noFSUFF3nbD",
    "reviewImg": "https://www.alternateending.com/wp-content/uploads/2019/12/sDNhWjd4X7c0oOlClkkwvqVOo45-1.jpg",
    "video": "https://www.youtube.com/watch?v=DiY1U7Jl6cA",
    "title": "Doctor Strange",
    "year": 2016,
    "date": "2016-11-04",
    "ageLimit": "13+",
    "length": "1h 55m",
    "category": ["Action"],
    "type": "Movie",
    "description": "A brilliant surgeon discovers the hidden world of mysticism and alternate dimensions, mastering magic to protect reality from dark forces and dangerous threats beyond ordinary comprehension.",
    "active": true
  },
  {
    "_id": 31,
    "titleImg": "https://image.tmdb.org/t/p/w500/yw5l9QAK8J9Tz4K2tKfN6G8h8DZ.jpg",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BMjM2NTQ5Mzc2M15BMl5BanBnXkFtZTgwNTcxMDI2NTE@._V1_FMjpg_UX1000_.jpg",
    "reviewImg": "hhttps://cdn.marvel.com/content/2x/antman_lob_mas_hlf_01_0.jpg",
    "video": "https://www.youtube.com/watch?v=1G4isv_Fylg",
    "title": "Ant-Man",
    "year": 2015,
    "date": "2015-07-17",
    "ageLimit": "13+",
    "length": "1h 57m",
    "category": ["Action"],
    "type": "Movie",
    "description": "Scott Lang becomes Ant-Man, using his shrinking suit and intellect to fight crime while balancing his personal life, family responsibilities, and the challenges of being a small hero with a big impact on the world.",
    "active": true
  },
  {
    "_id": 32,
    "titleImg": "https://image.tmdb.org/t/p/w500/6kbAMLteGO8yyewYau6bJ683sw7.jpg",
    "bgImg": "https://upload.wikimedia.org/wikipedia/en/3/33/Guardians_of_the_Galaxy_%28film%29_poster.jpg",
    "reviewImg": "https://wallpapers.com/images/hd/guardians-of-the-galaxy-2014-03j6q0os49l2rs02.jpg",
    "video": "https://www.youtube.com/watch?v=wb49-oV0F78",
    "title": "Guardians of the Galaxy",
    "year": 2014,
    "date": "2014-08-01",
    "ageLimit": "13+",
    "length": "2h 1m",
    "category": ["Action"],
    "type": "Movie",
    "description": "A group of misfit intergalactic criminals come together to stop a fanatical warrior, forming unlikely friendships and discovering courage, loyalty, and the true meaning of being heroes in a vast and dangerous universe.",
    "active": true
  },
  {
    "_id": 33,
    "titleImg": "https://image.tmdb.org/t/p/w500/8tZYtuWezp8JbcsvHYO0O46tFbo.jpg",
    "bgImg": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRB06zANAWkdMC2XZazOOJKxtCR7JvgTml-wQ&s",
    "reviewImg": "https://img1.hotstarext.com/image/upload/f_auto/sources/r1/cms/prod/1288/1371288-i-1e17c5bd66e5",
    "video": "https://www.youtube.com/watch?v=U3WCAw3Z8H0",
    "title": "Thor: Ragnarok",
    "year": 2017,
    "date": "2017-11-03",
    "ageLimit": "13+",
    "length": "2h 10m",
    "category": ["Action"],
    "type": "Movie",
    "description": "Thor must escape the alien planet Sakaar, survive gladiatorial battles, and prevent Ragnarok from destroying Asgard, learning leadership, teamwork, and resilience in a cosmic adventure full of humor and action.",
    "active": true
  },
  {
    "_id": 34,
    "titleImg": "https://image.tmdb.org/t/p/w500/6thLeu9TLf9HscOnwI9c48eLPYN.jpg",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BODY2MTAzOTQ4M15BMl5BanBnXkFtZTgwNzg5MTE0MjI@._V1_.jpg",
    "reviewImg": "https://i0.wp.com/straightfromamovie.com/wp-content/uploads/2017/07/spiderman-homecoming-2017.jpg?fit=1000%2C625&ssl=1",
    "video": "https://www.youtube.com/watch?v=QwievZ1Tx-8",
    "title": "Spider-Man: Homecoming",
    "year": 2017,
    "date": "2017-07-07",
    "ageLimit": "13+",
    "length": "2h 13m",
    "category": ["Action"],
    "type": "Movie",
    "description": "Peter Parker navigates life as a high school student while embracing his identity as Spider-Man, facing new villains, balancing responsibilities, and learning the consequences of heroism in his journey to become a true superhero.",
    "active": true
  },
  {
    "_id": 35,
    "titleImg": "https://image.tmdb.org/t/p/w500/6n8sFxZ11d1Hx2dKf3qjYc2bDh2.jpg",
    "bgImg": "https://lumiere-a.akamaihd.net/v1/images/p_drstrangeinthemultiverseofmadness_245_476cabb1.jpeg?region=0%2C0%2C540%2C810",
    "reviewImg": "https://cdn.mos.cms.futurecdn.net/NJXQ8h3mUd9mhsh2m8xpba.jpg",
    "video": "https://www.youtube.com/watch?v=8ugaeA-nMTc",
    "title": "Doctor Strange in the Multiverse of Madness",
    "year": 2022,
    "date": "2022-05-06",
    "ageLimit": "13+",
    "length": "2h 6m",
    "category": ["Action"],
    "type": "Movie",
    "description": "Doctor Strange navigates the multiverse with allies old and new, confronting mysterious adversaries and unpredictable threats, discovering the fragile balance of reality and the consequences of his actions across dimensions.",
    "active": true
  },
  {
    "_id": 36,
    "titleImg": "https://image.tmdb.org/t/p/w500/7VQwns7EgmIQ9xul7myXUqCjaF5.jpg",
    "bgImg": "https://fr.web.img2.acsta.net/pictures/21/06/30/13/37/5245550.jpg",
    "reviewImg": "https://w0.peakpx.com/wallpaper/531/229/HD-wallpaper-black-widow-movie-poster-2021.jpg",
    "video": "https://www.youtube.com/watch?v=HfI1WjG0X2c",
    "title": "Black Widow",
    "year": 2021,
    "date": "2021-07-09",
    "ageLimit": "13+",
    "length": "2h 14m",
    "category": ["Action"],
    "type": "Movie",
    "description": "Natasha Romanoff faces her past and confronts dangerous enemies while seeking redemption, revealing secrets of her history as a spy and challenging the boundaries between loyalty, family, and justice.",
    "active": true
  },
  {
    "_id": 37,
    "titleImg": "https://image.tmdb.org/t/p/w500/9EX3MyE0N4wXkHk6D7VvZG5e8.jpg",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BZmY5MDcyNzAtYzg3MC00MGNlLTg3OGItNmRjYThkZGVlNzAyXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    "reviewImg": "https://img1.hotstarext.com/image/upload/f_auto/sources/r1/cms/prod/9296/1369296-i-9c4de25be85b",
    "video": "https://www.youtube.com/watch?v=gbOgV7NkgH8",
    "title": "Shang-Chi and the Legend of the Ten Rings",
    "year": 2021,
    "date": "2021-09-03",
    "ageLimit": "13+",
    "length": "2h 12m",
    "category": ["Action"],
    "type": "Movie",
    "description": "Shang-Chi must confront his past and face the Ten Rings organization, mastering martial arts and inner strength while discovering family secrets, legacy, and the true meaning of heroism beyond physical combat.",
    "active": true
  },
  {
    "_id": 38,
    "titleImg": "https://image.tmdb.org/t/p/w500/6r4xG8Y5Lx1Hk5R2P6yJ7u1ZK1.jpg",
    "bgImg": "https://cdn.marvel.com/content/1x/eternals_lob_crd_06.jpg",
    "reviewImg": "https://www.thedigitalfix.com/wp-content/sites/thedigitalfix/2023/08/the-eternals-2-release-date-header.jpg",
    "video": "https://www.youtube.com/watch?v=0I0U5mPzW4A",
    "title": "Eternals",
    "year": 2021,
    "date": "2021-11-05",
    "ageLimit": "13+",
    "length": "2h 37m",
    "category": ["Action"],
    "type": "Movie",
    "description": "The immortal Eternals emerge to protect humanity from ancient threats, navigating complex relationships, moral dilemmas, and their hidden powers while confronting the destructive Deviants threatening Earth’s existence.",
    "active": true
  },
  {
    "_id": 39,
    "titleImg": "https://image.tmdb.org/t/p/w500/hfXf1s5v3Jz7h5I2G3mL6N3rTqk.jpg",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BMmFiZGZjMmEtMTA0Ni00MzA2LTljMTYtZGI2MGJmZWYzZTQ2XkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    "reviewImg": "https://images.saymedia-content.com/.image/ar_4:3%2Cc_fill%2Ccs_srgb%2Cfl_progressive%2Cq_auto:eco%2Cw_1200/MTkyMTk4OTI5OTE4NTM1MjE0/should-i-watch-spider-man-no-way-home-2021.jpg",
    "video": "https://www.youtube.com/watch?v=9Tg2Bf6xzS4",
    "title": "Spider-Man: No Way Home",
    "year": 2021,
    "date": "2021-12-17",
    "ageLimit": "13+",
    "length": "2h 28m",
    "category": ["Action"],
    "type": "Movie",
    "description": "Peter Parker faces multiverse consequences after his identity is revealed, confronting past and new villains while learning lessons about responsibility, heroism, and the importance of choices that shape reality.",
    "active": true
  },
  {
    "_id": 40,
    "titleImg": "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BMTczNTI2ODUwOF5BMl5BanBnXkFtZTcwMTU0NTIzMw@@._V1_FMjpg_UX1000_.jpg",
    "reviewImg": "https://image.tmdb.org/t/p/original/cyecB7godJ6kNHGONFjUyVN9OX5.jpg",
    "video": "https://www.youtube.com/watch?v=0WVDKZJkGlY",
    "title": "Iron Man (Special Edition)",
    "year": 2008,
    "date": "2008-05-02",
    "ageLimit": "13+",
    "length": "2h 6m",
    "category": ["Action"],
    "type": "Movie",
    "description": "In this special edition, Tony Stark’s journey as Iron Man is revisited, exploring his transformation, battles, and heroic feats while highlighting his personal growth, ethical dilemmas, and enduring fight against injustice.",
    "active": true
  },
  {
    "_id": 41,
    "titleImg": "https://image.tmdb.org/t/p/w500/hUtrCo9PH0loJqUKgz5TX4tSB3d.jpg",
    "bgImg": "https://m.media-amazon.com/images/I/91RNSMNJlsL._AC_SL1500_.jpg",
    "reviewImg": "https://indiqueipraver.com/wp-content/uploads/2022/02/781842.jpg",
    "video": "https://www.youtube.com/watch?v=HhesaQXLuRY",
    "title": "Breaking Bad",
    "year": 2008,
    "date": "2008-01-20",
    "ageLimit": "16+",
    "length": "5 Seasons",
    "category": ["Crime", "Drama"],
    "type": "Series",
    "description": "Walter White, a chemistry teacher turned methamphetamine producer, partners with former student Jesse Pinkman. As their empire grows, Walter descends into moral darkness, becoming one of TV’s most iconic anti-heroes.",
    "trend": true,
    "active": true
  },
  {
    "_id": 42,
    "titleImg": "../images/wednesday-title.png",
    "bgImg": "https://i.ebayimg.com/images/g/PucAAOSw7kpjzvMi/s-l1200.jpg",
    "reviewImg": "https://images.hdqwalls.com/wallpapers/netflix-wednesday-season-2-bj.jpg",
    "video": "videos/wednesday-trailer.mp4",
    "title": "Wednesday",
    "year": 2022,
    "date": "2022-11-23",
    "ageLimit": "13+",
    "length": "1 Season",
    "category": ["Comedy", "Mystery", "Fantasy"],
    "type": "Series",
    "description": "Wednesday Addams enrolls at Nevermore Academy, where she investigates a series of murders while discovering her psychic abilities, solving mysteries, and dealing with eccentric classmates and rivals.",
    "active": true,
    "trend": true
  },
  {
    "_id": 43,
    "titleImg": "../images/squidgame-title.png",
    "bgImg": "https://m.media-amazon.com/images/I/7118ecsxO3L._UF894,1000_QL80_.jpg",
    "reviewImg": "https://sm.ign.com/t/ign_in/feature/s/squid-game/squid-game-season-3-ending-explained-the-game-isnt-over-yet_td74.1280.jpg",
    "video": "videos/squidgame-trailer.mp4",
    "title": "Squid Game",
    "year": 2021,
    "date": "2021-09-17",
    "ageLimit": "18+",
    "length": "1 Season",
    "category": ["Thriller", "Drama"],
    "type": "Series",
    "description": "Hundreds of cash-strapped players accept a mysterious invitation to compete in deadly children's games, where the stakes are life and death, and only one can walk away with the prize money.",
    "active": true,
    "trend": true
  },
  {
    "_id": 44,
    "titleImg": "https://image.tmdb.org/t/p/w500/wNBQ1Yqz6W0ZAKw5nlFJGzGbL8D.jpg",
    "bgImg": "https://www.tallengestore.com/cdn/shop/products/PeakyBlinders-NetflixTVShow-ArtPoster_56823192-0a33-4a9d-b8e3-fd2878fcc867_large.jpg?v=1619864550",
    "reviewImg": "https://cdn.webshopapp.com/shops/268192/files/433182623/the-peaky-blinders.jpg",
    "video": "https://www.youtube.com/watch?v=RRKJiM9Njr8",
    "title": "Peaky Blinders",
    "year": 2013,
    "date": "2013-09-12",
    "ageLimit": "16+",
    "length": "6 Seasons",
    "category": ["Crime", "Drama"],
    "type": "Series",
    "description": "Thomas Shelby leads the notorious Shelby crime family in post-war Birmingham. As their empire expands, they face rivals, political intrigue, and personal tragedies in this gritty, stylish gangster drama.",
    "trend": true,
    "active": true
  },
  {
    "_id": 45,
    "titleImg": "https://image.tmdb.org/t/p/w500/3t0vK5kR1EnNbF1u1jHozVnYg7W.jpg",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BNTc0YmQxMjEtODI5MC00NjFiLTlkMWUtOGQ5NjFmYWUyZGJhXkEyXkFqcGc@._V1_.jpg",
    "reviewImg": "https://poundarts.org.uk/wp-content/uploads/2024/05/Dune-Part-Two.jpg",
    "video": "https://www.youtube.com/watch?v=mYfJxlgR2jw",
    "title": "Dune: Part Two",
    "year": 2024,
    "date": "2024-03-01",
    "ageLimit": "13+",
    "length": "2h 45m",
    "category": ["Sci-Fi", "Adventure"],
    "type": "Movie",
    "description": "Paul Atreides unites with the Fremen to lead a rebellion against the Harkonnens, seeking vengeance for his family while grappling with destiny, politics, and love in the sweeping continuation of the Dune saga.",
    "trend": true,
    "active": true
  },
  {
    "_id": 46,
    "titleImg": "https://image.tmdb.org/t/p/w500/7JyxqfMEXg3A2kZZgwyU0vbzUKk.jpg",
    "bgImg": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSXlsN2uwcWeTVb4yo09ce1V9S8AnosT2qHpA&s",
    "reviewImg": "https://bloody-disgusting.com/wp-content/uploads/2022/11/last-of-us-tv-2.png",
    "video": "https://www.youtube.com/watch?v=FmQ6kaV0Dk4",
    "title": "The Last of Us",
    "year": 2023,
    "date": "2023-01-15",
    "ageLimit": "16+",
    "length": "1 Season",
    "category": ["Drama", "Horror"],
    "type": "Series",
    "description": "Joel and Ellie journey through a post-apocalyptic America ravaged by a fungal infection, forming a deep bond as they face deadly threats, emotional trials, and moral dilemmas in this acclaimed adaptation of the hit video game.",
    "trend": true,
    "active": true
  },
  {
    "_id": 47,
    "titleImg": "https://image.tmdb.org/t/p/w500/zQH8dZx1SgjM7RHh2P6uXe3G4kL.jpg",
    "bgImg": "https://upload.wikimedia.org/wikipedia/en/thumb/4/4a/Oppenheimer_%28film%29.jpg/250px-Oppenheimer_%28film%29.jpg",
    "reviewImg": "https://static0.cbrimages.com/wordpress/wp-content/uploads/2023/07/oppenheimer_movie_nolan.jpg",
    "video": "https://www.youtube.com/watch?v=5xH0HfJHsaY",
    "title": "Oppenheimer",
    "year": 2023,
    "date": "2023-07-21",
    "ageLimit": "16+",
    "length": "3h",
    "category": ["Biography", "Drama"],
    "type": "Movie",
    "description": "J. Robert Oppenheimer’s story unfolds as he leads the Manhattan Project, creating the atomic bomb and facing moral, political, and personal consequences. Christopher Nolan’s epic explores the birth of the nuclear age.",
    "trend": true,
    "active": true
  },
  {
    "_id": 48,
    "titleImg": "../images/strangerthings-title.png",
    "bgImg": "https://posterwa.com/cdn/shop/products/STR4.jpg?v=1659647172",
    "reviewImg": "https://www.tallengestore.com/cdn/shop/products/stranger_things_1_756ad630-b491-41d3-89c8-170c6299d358.jpg?v=1514020602",
    "video": "videos/strangerthings-trailer.mp4",
    "title": "Stranger Things",
    "year": 2016,
    "date": "2016-07-15",
    "ageLimit": "16+",
    "length": "4 Seasons",
    "category": ["Sci-Fi", "Thriller", "Drama"],
    "type": "Series",
    "description": "A group of kids in a small town uncover supernatural secrets, dark experiments, and a parallel dimension known as the Upside Down, as they fight to save their friends and family from monstrous threats.",
    "active": true,
    "trend": true
  },
  {
    "_id": 49,
    "titleImg": "../images/dark-title.png",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BZTE1YTczZWUtNTI5Ny00NzI0LWFmODctYzZiYzQ3MmRmOWZlXkEyXkFqcGc@._V1_.jpg",
    "reviewImg": "hhttps://i0.wp.com/333horror.com/wp-content/uploads/2021/02/season-1-wallpaper.jpg",
    "video": "videos/dark-trailer.mp4",
    "title": "Dark",
    "year": 2017,
    "date": "2017-12-01",
    "ageLimit": "16+",
    "length": "3 Seasons",
    "category": ["Mystery", "Sci-Fi", "Thriller"],
    "type": "Series",
    "description": "In a small German town, the disappearance of two children exposes the secrets of four families and a supernatural mystery that spans multiple generations and timelines, challenging fate and free will.",
    "active": true,
    "trend": true
  }, {
    "_id": 50,
    "titleImg": "https://image.tmdb.org/t/p/w500/7ZO9yoEU2fAHKhmJWfAc2QIPWJg.jpg",
    "bgImg": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ005ecBMcdT2VzU_m4O26-CbVYsC8E5AmURw&s",
    "reviewImg": "https://assets-prd.ignimgs.com/2023/09/26/blogroll-creator-review-1695740984192.jpg",
    "video": "https://www.youtube.com/watch?v=aOb15GVFZxU",
    "title": "The Creator",
    "year": 2023,
    "date": "2023-09-29",
    "ageLimit": "13+",
    "length": "2h 13m",
    "category": ["Sci-Fi", "Thriller"],
    "type": "Movie",
    "description": "In a war between humans and AI, a soldier discovers a weapon that could end all conflict: an advanced AI child. He must decide between duty and protecting the future of humanity and machines.",
    "trend": true,
    "active": true
  },
  {
    "_id": 51,
    "titleImg": "../images/dexter-title.png",
    "bgImg": "https://i.ebayimg.com/images/g/EQsAAOSwgv5ZTlGk/s-l1200.jpg",
    "reviewImg": "https://ntvb.tmsimg.com/assets/p185267_b_h10_aa.jpg?w=960&h=540",
    "video": "videos/dexter-trailer.mp4",
    "title": "Dexter",
    "year": 2021,
    "date": "2021-11-07",
    "ageLimit": "18+",
    "length": "9 Seasons",
    "category": ["Crime", "Thriller", "Drama"],
    "type": "Series",
    "description": "Dexter Morgan is a Miami-based blood splatter expert who leads a secret life as a vigilante serial killer, targeting murderers who escaped justice. The 2021 revival 'Dexter: New Blood' continues his dark story in a chilling new setting.",
    "active": true,
    "trend": true
  },
  {
    "_id": 52,
    "titleImg": "images/the-naked-gun-title.png",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BNGFlNDhkNzItZjgxNC00OGYzLWFjZDAtZTJmNDY5ZmEyZDc0XkEyXkFqcGc@._V1_.jpg",
    "reviewImg": "https://www.phoenixmag.com/wp-content/uploads/2025/08/Screen-Shot-2025-08-04-at-11.42.09-AM.png",
    "video": "videos/the-naked-gun-trailer.mp4",
    "title": "The Naked Gun",
    "year": 2025,
    "date": "2025-08-01",
    "ageLimit": "15+",
    "length": "85 min",
    "category": ["Action", "Comedy", "Crime"],
    "type": "Movie",
    "description": "Legacy sequel to the Naked Gun franchise. Lt. Frank Drebin Jr., played by Liam Neeson, takes center stage in this comedic action thriller. :contentReference[oaicite:0]{index=0}",
    "active": true,
    "latest": true
  },
  {
    "_id": 53,
    "titleImg": "images/sinners-title.png",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BNjIwZWY4ZDEtMmIxZS00NDA4LTg4ZGMtMzUwZTYyNzgxMzk5XkEyXkFqcGc@._V1_.jpg",
    "reviewImg": "https://via.placeholder.com/960x540.png?text=Review+Sinners",
    "video": "videos/sinners-trailer.mp4",
    "title": "Sinners",
    "year": 2025,
    "date": "2025-04-18",
    "ageLimit": "18+",
    "length": "≈ 2h",
    "category": ["Drama"],
    "type": "Movie",
    "description": "A dramatic film released in the spring of 2025, using both standard and IMAX 70 mm prints. :contentReference[oaicite:1]{index=1}",
    "active": true,
    "latest": true
  },
  {
    "_id": 54,
    "titleImg": "images/how-to-train-your-dragon-title.png",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BMjIwMDIwNjAyOF5BMl5BanBnXkFtZTgwNDE1MDc2NTM@._V1_FMjpg_UX1000_.jpg",
    "reviewImg": "https://static0.moviewebimages.com/wordpress/wp-content/uploads/article/evkgjS87YJyxAttm7AW0s2V6c6Wqj5.jpg",
    "video": "videos/httyd-trailer.mp4",
    "title": "How to Train Your Dragon",
    "year": 2025,
    "date": "2025-06-13",
    "ageLimit": "PG-13",
    "length": "≈ 2h",
    "category": ["Adventure", "Fantasy", "Family"],
    "type": "Movie",
    "description": "Live-action remake/adaptation of the animated trilogy, featuring lands, dragons & classic adventure. :contentReference[oaicite:2]{index=2}",
    "active": true,
    "latest": true
  },
  {
    "_id": 55,
    "titleImg": "images/tron-ares-title.png",
    "bgImg": "https://cdna.artstation.com/p/assets/images/images/086/748/458/large/visualbarrage-tron-ares-2025-movie-poster.jpg?1743986323",
    "reviewImg": "https://miro.medium.com/v2/resize:fit:1400/0*v8EWiokRl2GaExsa",
    "video": "videos/tron-ares-trailer.mp4",
    "title": "Tron: Ares",
    "year": 2025,
    "date": "2025-10-10",
    "ageLimit": "PG-13",
    "length": "TBD",
    "category": ["Sci-Fi", "Action"],
    "type": "Movie",
    "description": "A new entry in the Tron universe. The film expands on the digital realm with new stakes & characters. :contentReference[oaicite:3]{index=3}",
    "active": true,
    "latest": true
  },
  {
    "_id": 56,
    "titleImg": "images/conjuring-last-rites-title.png",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BMTM3NjA1NDMyMV5BMl5BanBnXkFtZTcwMDQzNDMzOQ@@._V1_FMjpg_UX1000_.jpg",
    "reviewImg": "https://wallpapers.com/images/hd/the-conjuring-poster-y2bs1yiiscn9qdio.jpg",
    "video": "videos/conjuring-last-rites-trailer.mp4",
    "title": "The Conjuring: Last Rites",
    "year": 2025,
    "date": "2025-09-05",
    "ageLimit": "18+",
    "length": "TBD",
    "category": ["Horror", "Thriller"],
    "type": "Movie",
    "description": "Latest installment in The Conjuring franchise; big box-office horror success. :contentReference[oaicite:4]{index=4}",
    "active": true,
    "latest": true
  },
  {
    "_id": 57,
    "titleImg": "https://media.cimanow.cc/wp-content/uploads/2025/07/%D9%81%D9%8A%D9%84%D9%85-Mission-Impossible-The-Final-Reckoning-2025-%D9%85%D8%AA%D8%B1%D8%AC%D9%85-%D9%84%D9%88%D8%AC%D9%88.png",
    "bgImg": "https://media.cimanow.cc/wp-content/uploads/2025/07/%D9%81%D9%8A%D9%84%D9%85-Mission-Impossible-The-Final-Reckoning-2025-%D9%85%D8%AA%D8%B1%D8%AC%D9%85.jpg",
    "reviewImg": "https://media.cimanow.cc/wp-content/uploads/2025/07/%D9%81%D9%8A%D9%84%D9%85-Mission-Impossible-The-Final-Reckoning-2025-%D9%85%D8%AA%D8%B1%D8%AC%D9%85-%D9%83%D9%88%D9%81%D8%B1.jpg",
    "video": "videos/mi-final-reckoning-trailer.mp4",
    "title": "Mission: Impossible - The Final Reckoning",
    "year": 2025,
    "date": "2025-05-23",
    "ageLimit": "PG-13",
    "length": "≈ 2h 20 min",
    "category": ["Action", "Adventure", "Spy"],
    "type": "Movie",
    "description": "The newest in the long-running MI franchise; high action, stunts, global scale. :contentReference[oaicite:5]{index=5}",
    "active": true,
    "latest": true
  },
  {
    "_id": 58,
    "titleImg": "images/thug-life-title.png",
    "bgImg": "https://via.placeholder.com/800x450.png?text=Thug+Life+2025",
    "reviewImg": "https://via.placeholder.com/960x540.png?text=Review+Thug+Life",
    "video": "videos/thug-life-trailer.mp4",
    "title": "Thug Life",
    "year": 2025,
    "date": "2025-06-05",
    "ageLimit": "18+",
    "length": "163 min",
    "category": ["Action", "Drama"],
    "type": "Movie",
    "description": "Indian Tamil gangster action/drama by Mani Ratnam, combining themes of betrayal, power, and redemption. :contentReference[oaicite:6]{index=6}",
    "active": true,
    "latest": true
  },
  {
    "_id": 59,
    "titleImg": "images/freakier-friday-title.png",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BY2Q0M2NmMjctODEwMi00NGIyLTk4NjUtMzBlNDAxYTZlZGJiXkEyXkFqcGc@._V1_FMjpg_UX1000_.jpg",
    "reviewImg": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXwcsQVTkVYdrE90AlsUzwUz8FeQ2fKtvfk5s-5GXYetTRvNa-oUObMh9DRzSNm3OLGiA&usqp=CAU",
    "video": "videos/freakier-friday-trailer.mp4",
    "title": "Freakier Friday",
    "year": 2025,
    "date": "2025-08-08",
    "ageLimit": "PG-13",
    "length": "TBD",
    "category": ["Comedy", "Family"],
    "type": "Movie",
    "description": "A new sequel to the 2003 comedy. It pits chaos and comedic identity mix-ups in a family setting. :contentReference[oaicite:7]{index=7}",
    "active": true,
    "latest": true
  },
  {
    "_id": 60,
    "titleImg": "https://media.cimanow.cc/wp-content/uploads/2022/05/%D9%81%D9%8A%D9%84%D9%85-The-Bad-Guys-2022-%D9%85%D8%AA%D8%B1%D8%AC%D9%85-%D9%84%D9%88%D8%AC%D9%88.png",
    "bgImg": "https://media.cimanow.cc/wp-content/uploads/2022/05/%D9%81%D9%8A%D9%84%D9%85-The-Bad-Guys-2022-%D9%85%D8%AA%D8%B1%D8%AC%D9%85.jpg",
    "reviewImg": "https://media.cimanow.cc/wp-content/uploads/2022/05/%D9%81%D9%8A%D9%84%D9%85-The-Bad-Guys-2022-%D9%85%D8%AA%D8%B1%D8%AC%D9%85-%D9%83%D9%88%D9%81%D8%B1.jpg",
    "video": "videos/bad-guys-2-trailer.mp4",
    "title": "The Bad Guys 2",
    "year": 2025,
    "date": "2025-08-01",
    "ageLimit": "PG",
    "length": "TBD",
    "category": ["Animation", "Family", "Comedy"],
    "type": "Movie",
    "description": "Sequel to the animated hit, with returning characters facing new trouble. :contentReference[oaicite:8]{index=8}",
    "active": true,
    "latest": true
  },
  {
    "_id": 61,
    "titleImg": "https://media.cimanow.cc/wp-content/uploads/2025/09/%D9%81%D9%8A%D9%84%D9%85-Weapons-2025-%D9%85%D8%AA%D8%B1%D8%AC%D9%85-%D9%84%D9%88%D8%AC%D9%88.png",
    "bgImg": "https://media.cimanow.cc/wp-content/uploads/2025/09/%D9%81%D9%8A%D9%84%D9%85-Weapons-2025-%D9%85%D8%AA%D8%B1%D8%AC%D9%85.jpg",
    "reviewImg": "https://media.cimanow.cc/wp-content/uploads/2025/09/%D9%81%D9%8A%D9%84%D9%85-Weapons-2025-%D9%85%D8%AA%D8%B1%D8%AC%D9%85-%D9%83%D9%88%D9%81%D8%B1.jpg",
    "video": "videos/weapons-trailer.mp4",
    "title": "Weapons",
    "year": 2025,
    "date": "2025-08-08",
    "ageLimit": "18+",
    "length": "TBD",
    "category": ["Horror", "Thriller"],
    "type": "Movie",
    "description": "From the director of Barbarian, a follow-up horror/thriller that builds on suspense and dread. :contentReference[oaicite:9]{index=9}",
    "active": true,
    "latest": true
  },
  {
    "_id": 62,
    "titleImg": "https://upload.wikimedia.org/path/to/dune2-title.png",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BZDU5NTM1NzUt.jpg",
    "reviewImg": "https://m.media-amazon.com/images/M/MV5BM2I4.jpg",
    "video": "videos/dune2-trailer.mp4",
    "title": "Dune: Part Two",
    "year": 2025,
    "date": "2025-03-15",
    "ageLimit": "13+",
    "length": "2h 46m",
    "category": ["Sci-Fi", "Adventure"],
    "type": "Movie",
    "description": "Paul Atreides unites with the Fremen to wage war against the conspirators who destroyed his family.",
    "rating": 9.2,
    "active": true,

  },
  {
    "_id": 63,
    "titleImg": "https://upload.wikimedia.org/path/to/joker2-title.png",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BJGFi.jpg",
    "reviewImg": "https://m.media-amazon.com/images/M/MV5BYjM5.jpg",
    "video": "videos/joker2-trailer.mp4",
    "title": "Joker: Folie à Deux",
    "year": 2025,
    "date": "2025-10-04",
    "ageLimit": "18+",
    "length": "2h 12m",
    "category": ["Drama", "Crime", "Musical"],
    "type": "Movie",
    "description": "Arthur Fleck returns, with Harley Quinn by his side, blurring the lines between reality and madness.",
    "rating": 8.8,
    "active": true,

  },
  {
    "_id": 64,
    "titleImg": "https://upload.wikimedia.org/path/to/deadpool3-title.png",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BYzZk.jpg",
    "reviewImg": "https://m.media-amazon.com/images/M/MV5BZmM4.jpg",
    "video": "videos/deadpool3-trailer.mp4",
    "title": "Deadpool & Wolverine",
    "year": 2025,
    "date": "2025-07-26",
    "ageLimit": "18+",
    "length": "2h 10m",
    "category": ["Action", "Comedy"],
    "type": "Movie",
    "description": "Deadpool teams up with Wolverine in an R-rated multiverse adventure full of humor and chaos.",
    "rating": 9.0,
    "active": true,

  },
  {
    "_id": 65,
    "titleImg": "https://upload.wikimedia.org/path/to/insideout2-title.png",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BY2Ux.jpg",
    "reviewImg": "https://m.media-amazon.com/images/M/MV5BMGM1.jpg",
    "video": "videos/insideout2-trailer.mp4",
    "title": "Inside Out 2",
    "year": 2025,
    "date": "2025-06-14",
    "ageLimit": "7+",
    "length": "1h 50m",
    "category": ["Animation", "Comedy", "Family"],
    "type": "Movie",
    "description": "Riley is now a teenager dealing with new emotions, including Anxiety, Envy, and Embarrassment.",
    "rating": 8.4,
    "active": true,

  },
  {
    "_id": 66,
    "titleImg": "https://upload.wikimedia.org/path/to/mufasa-title.png",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BMmQ3.jpg",
    "reviewImg": "https://m.media-amazon.com/images/M/MV5BZTRl.jpg",
    "video": "videos/mufasa-trailer.mp4",
    "title": "Mufasa: The Lion King",
    "year": 2025,
    "date": "2025-12-20",
    "ageLimit": "7+",
    "length": "TBD",
    "category": ["Adventure", "Drama", "Family"],
    "type": "Movie",
    "description": "The origin story of Mufasa, exploring how he became the great king of the Pride Lands.",
    "rating": 8.1,
    "active": true,

  },
  {
    "_id": 67,
    "titleImg": "https://upload.wikimedia.org/path/to/gladiator2-title.png",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BZTg2.jpg",
    "reviewImg": "https://m.media-amazon.com/images/M/MV5BZGI1.jpg",
    "video": "videos/gladiator2-trailer.mp4",
    "title": "Gladiator 2",
    "year": 2025,
    "date": "2025-11-15",
    "ageLimit": "16+",
    "length": "TBD",
    "category": ["Action", "Drama"],
    "type": "Movie",
    "description": "A follow-up to the iconic Gladiator, focusing on Lucius, the son of Maximus' lover.",
    "rating": 8.7,
    "active": true,

  },
  {
    "_id": 68,
    "titleImg": "https://upload.wikimedia.org/path/to/venom3-title.png",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BYzIx.jpg",
    "reviewImg": "https://m.media-amazon.com/images/M/MV5BMzFk.jpg",
    "video": "videos/venom3-trailer.mp4",
    "title": "Venom: The Last Dance",
    "year": 2025,
    "date": "2025-10-24",
    "ageLimit": "13+",
    "length": "TBD",
    "category": ["Action", "Sci-Fi"],
    "type": "Movie",
    "description": "Eddie Brock and Venom face their most dangerous threat yet in this final installment.",
    "rating": 7.9,
    "active": true,

  },
  {
    "_id": 69,
    "titleImg": "https://upload.wikimedia.org/path/to/wicked-title.png",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BZTM3.jpg",
    "reviewImg": "https://m.media-amazon.com/images/M/MV5BYjUw.jpg",
    "video": "videos/wicked-trailer.mp4",
    "title": "Wicked: Part One",
    "year": 2025,
    "date": "2025-11-27",
    "ageLimit": "PG",
    "length": "TBD",
    "category": ["Musical", "Fantasy"],
    "type": "Movie",
    "description": "A cinematic adaptation of the beloved Broadway musical exploring the witches of Oz.",
    "rating": 8.5,
    "active": true,

  },
  {
    "_id": 70,
    "titleImg": "https://upload.wikimedia.org/path/to/sonic3-title.png",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BZjNl.jpg",
    "reviewImg": "https://m.media-amazon.com/images/M/MV5BZmUw.jpg",
    "video": "videos/sonic3-trailer.mp4",
    "title": "Sonic the Hedgehog 3",
    "year": 2025,
    "date": "2025-12-19",
    "ageLimit": "PG",
    "length": "TBD",
    "category": ["Action", "Comedy", "Family"],
    "type": "Movie",
    "description": "Sonic teams up with Tails and Knuckles again to face Shadow the Hedgehog in an epic showdown.",
    "rating": 8.3,
    "active": true,

  },
  {
    "_id": 71,
    "titleImg": "https://upload.wikimedia.org/path/to/sm5-title.png",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BNzdh.jpg",
    "reviewImg": "https://m.media-amazon.com/images/M/MV5BYzlj.jpg",
    "video": "videos/sm5-trailer.mp4",
    "title": "Spider-Man 5 (MCU)",
    "year": 2025,
    "date": "2025-12-17",
    "ageLimit": "13+",
    "length": "TBD",
    "category": ["Action", "Superhero"],
    "type": "Movie",
    "description": "Peter Parker faces a new threat that tests his identity and future as Spider-Man.",
    "rating": 9.1,
    "active": true,

  },
  {
    "_id": 72,
    "titleImg": "https://upload.wikimedia.org/path/to/mission8-title.png",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BZmRk.jpg",
    "reviewImg": "https://m.media-amazon.com/images/M/MV5BZDQ3.jpg",
    "video": "videos/mission8-trailer.mp4",
    "title": "Mission: Impossible – Reckoning Part Two",
    "year": 2025,
    "date": "2025-06-27",
    "ageLimit": "13+",
    "length": "TBD",
    "category": ["Action", "Thriller"],
    "type": "Movie",
    "description": "Ethan Hunt faces the conclusion of his most dangerous mission yet.",
    "rating": 8.6,
    "active": true
  },
  {
    "_id": 73,
    "titleImg": "https://upload.wikimedia.org/path/to/johnwick5-title.png",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BM2Y3.jpg",
    "reviewImg": "https://m.media-amazon.com/images/M/MV5BMjJm.jpg",
    "video": "videos/johnwick5-trailer.mp4",
    "title": "John Wick: Chapter 5",
    "year": 2025,
    "date": "2025-09-12",
    "ageLimit": "18+",
    "length": "TBD",
    "category": ["Action", "Crime", "Thriller"],
    "type": "Movie",
    "description": "John Wick returns for one last bloody chapter of vengeance and redemption.",
    "rating": 9.0,
    "active": true
  },
  {
    "_id": 74,
    "titleImg": "https://upload.wikimedia.org/path/to/fast11-title.png",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BYTQ3.jpg",
    "reviewImg": "https://m.media-amazon.com/images/M/MV5BNmM1.jpg",
    "video": "videos/fast11-trailer.mp4",
    "title": "Fast & Furious 11",
    "year": 2025,
    "date": "2025-04-18",
    "ageLimit": "13+",
    "length": "TBD",
    "category": ["Action", "Adventure"],
    "type": "Movie",
    "description": "Dom and the crew gear up for their final ride with higher stakes than ever.",
    "rating": 7.8,
    "active": true
  },
  {
    "_id": 75,
    "titleImg": "https://upload.wikimedia.org/path/to/expendables5-title.png",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BMzU4.jpg",
    "reviewImg": "https://m.media-amazon.com/images/M/MV5BODQz.jpg",
    "video": "videos/expendables5-trailer.mp4",
    "title": "The Expendables 5",
    "year": 2025,
    "date": "2025-08-01",
    "ageLimit": "18+",
    "length": "TBD",
    "category": ["Action"],
    "type": "Movie",
    "description": "Barney Ross leads the ultimate team for one last explosive mission.",
    "rating": 7.5,
    "active": true
  },
  {
    "_id": 76,
    "titleImg": "https://upload.wikimedia.org/path/to/grey-man2-title.png",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BNzBh.jpg",
    "reviewImg": "https://m.media-amazon.com/images/M/MV5BZGY3.jpg",
    "video": "videos/greyman2-trailer.mp4",
    "title": "The Gray Man 2",
    "year": 2025,
    "date": "2025-05-09",
    "ageLimit": "16+",
    "length": "TBD",
    "category": ["Action", "Thriller"],
    "type": "Movie",
    "description": "Court Gentry faces a new shadow organization that threatens global stability.",
    "rating": 8.0,
    "active": true
  },
  {
    "_id": 77,
    "titleImg": "https://upload.wikimedia.org/path/to/extraction3-title.png",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BN2Y4.jpg",
    "reviewImg": "https://m.media-amazon.com/images/M/MV5BYjIz.jpg",
    "video": "videos/extraction3-trailer.mp4",
    "title": "Extraction 3",
    "year": 2025,
    "date": "2025-07-04",
    "ageLimit": "18+",
    "length": "TBD",
    "category": ["Action", "Thriller"],
    "type": "Movie",
    "description": "Tyler Rake is back for another dangerous extraction mission in enemy territory.",
    "rating": 8.4,
    "active": true
  },
  {
    "_id": 78,
    "titleImg": "https://upload.wikimedia.org/path/to/reacher-title.png",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BZDkx.jpg",
    "reviewImg": "https://m.media-amazon.com/images/M/MV5BZjY5.jpg",
    "video": "videos/reacher-trailer.mp4",
    "title": "Reacher: Never Go Back Again",
    "year": 2025,
    "date": "2025-09-19",
    "ageLimit": "16+",
    "length": "TBD",
    "category": ["Action", "Mystery"],
    "type": "Movie",
    "description": "Jack Reacher finds himself entangled in a deadly conspiracy with military ties.",
    "rating": 7.9,
    "active": true
  },
  {
    "_id": 79,
    "titleImg": "https://upload.wikimedia.org/path/to/shadow-force-title.png",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BNzli.jpg",
    "reviewImg": "https://m.media-amazon.com/images/M/MV5BMzBi.jpg",
    "video": "videos/shadowforce-trailer.mp4",
    "title": "Shadow Force",
    "year": 2025,
    "date": "2025-05-23",
    "ageLimit": "16+",
    "length": "TBD",
    "category": ["Action"],
    "type": "Movie",
    "description": "A black ops team goes rogue when their own government turns against them.",
    "rating": 7.7,
    "active": true
  },
  {
    "_id": 80,
    "titleImg": "https://upload.wikimedia.org/path/to/atomic-blonde2-title.png",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BZTU3.jpg",
    "reviewImg": "https://m.media-amazon.com/images/M/MV5BYzMz.jpg",
    "video": "videos/atomicblonde2-trailer.mp4",
    "title": "Atomic Blonde 2",
    "year": 2025,
    "date": "2025-08-29",
    "ageLimit": "18+",
    "length": "TBD",
    "category": ["Action", "Spy"],
    "type": "Movie",
    "description": "Lorraine Broughton returns with another mission in the world of espionage and betrayal.",
    "rating": 8.2,
    "active": true
  },
  {
    "_id": 81,
    "titleImg": "https://upload.wikimedia.org/path/to/rogue-nation-title.png",
    "bgImg": "https://m.media-amazon.com/images/M/MV5BM2Y4.jpg",
    "reviewImg": "https://m.media-amazon.com/images/M/MV5BZmU5.jpg",
    "video": "videos/roguenation-trailer.mp4",
    "title": "Rogue Nation",
    "year": 2025,
    "date": "2025-10-10",
    "ageLimit": "18+",
    "length": "TBD",
    "category": ["Action", "Military"],
    "type": "Movie",
    "description": "When a rogue general seizes nuclear codes, an elite unit must stop global catastrophe.",
    "rating": 8.3,
    "active": true
  }


];

export default moviesData;